//! Event handling pipeline for the generic Kafka watcher.
//!
//! This module defines the central pipeline step that converts a raw Kafka
//! message into an executable [`GenericTask`]. The pipeline is embodied by
//! [`GenericEventHandler`], which performs the following steps in order:
//!
//! 1. Parse the raw payload into a [`GenericPlanEvent`] (early validation).
//! 2. Optionally evaluate a [`GenericMatcher`] to filter the event.
//! 3. Optionally resolve a plan file from a curated on-disk directory.
//! 4. Re-validate the resolved plan.
//! 5. Derive an instruction string and return a [`GenericTask`].
//!
//! # Plan directory resolution
//!
//! When `plan_directory` is `Some(dir)`, the handler searches for an
//! on-disk plan file using the following priority order:
//!
//! 1. `{dir}/{plan.name}-{version}.yaml` — when the event carries a version.
//! 2. `{dir}/{plan.name}.yaml` — name-only fallback.
//! 3. The embedded plan from the Kafka payload — when no file is found.
//!
//! If a candidate file is found but cannot be parsed, an error is returned
//! immediately (parse failures are not silently swallowed).
//!
//! # Examples
//!
//! ```
//! use xzatoma::config::GenericMatchConfig;
//! use xzatoma::watcher::generic::event::RawKafkaMessage;
//! use xzatoma::watcher::generic::event_handler::GenericEventHandler;
//!
//! # #[tokio::main]
//! # async fn main() -> anyhow::Result<()> {
//! let handler = GenericEventHandler::new(None, None);
//!
//! let msg = RawKafkaMessage {
//!     payload: "name: deploy\nsteps:\n  - name: s1\n    action: echo hi\n".to_string(),
//!     topic: "plans.input".to_string(),
//!     key: Some("corr-123".to_string()),
//! };
//!
//! let task = handler.handle(msg).await?;
//! assert!(task.is_some());
//! let task = task.unwrap();
//! assert_eq!(task.plan.name, "deploy");
//! assert!(!task.instruction.is_empty());
//! # Ok(())
//! # }
//! ```

use crate::error::Result;
use crate::tools::plan::{Plan, PlanParser};
use crate::watcher::generic::event::{GenericPlanEvent, RawKafkaMessage};
use crate::watcher::generic::matcher::GenericMatcher;
use chrono::{DateTime, Utc};
use std::path::{Path, PathBuf};
use tracing::{debug, info};

/// A fully parsed and validated plan task ready for agent execution.
///
/// `GenericTask` is the output of the [`GenericEventHandler`] pipeline. It
/// carries the resolved (and possibly overridden by a directory file) plan,
/// the instruction string that will be passed to the agent executor, the
/// optional Kafka message key used for result correlation, and the UTC
/// timestamp at which the triggering Kafka message was received and parsed.
///
/// # Examples
///
/// ```
/// use xzatoma::watcher::generic::event::RawKafkaMessage;
/// use xzatoma::watcher::generic::event_handler::GenericEventHandler;
///
/// # #[tokio::main]
/// # async fn main() -> anyhow::Result<()> {
/// let handler = GenericEventHandler::new(None, None);
/// let msg = RawKafkaMessage {
///     payload: "name: deploy\nsteps:\n  - name: s1\n    action: echo ok\n".to_string(),
///     topic: "t".to_string(),
///     key: Some("corr-abc".to_string()),
/// };
/// let task = handler.handle(msg).await?.unwrap();
/// assert_eq!(task.plan.name, "deploy");
/// assert_eq!(task.correlation_key.as_deref(), Some("corr-abc"));
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct GenericTask {
    /// The resolved and validated plan.
    pub plan: Plan,

    /// The instruction string derived from the plan for the agent executor.
    ///
    /// Generated by [`Plan::to_instruction`] from the resolved plan.
    pub instruction: String,

    /// Optional Kafka message key used to correlate this task with its result.
    ///
    /// Maps to the `trigger_event_id` field of the published
    /// [`GenericPlanResult`](crate::watcher::generic::result_event::GenericPlanResult).
    pub correlation_key: Option<String>,

    /// UTC timestamp of when the triggering Kafka message was received and parsed.
    pub received_at: DateTime<Utc>,
}

/// Centralized event parsing and matching pipeline for the generic watcher.
///
/// `GenericEventHandler` converts a [`RawKafkaMessage`] into an optional
/// [`GenericTask`] through a five-step pipeline:
///
/// 1. **Parse**: call [`GenericPlanEvent::new`] on the raw payload.
/// 2. **Match**: if a [`GenericMatcher`] is configured, reject unmatched events.
/// 3. **Resolve**: if a plan directory is configured, look for an on-disk plan.
/// 4. **Validate**: call [`PlanParser::validate`] on the resolved plan.
/// 5. **Build task**: derive the instruction and return [`GenericTask`].
///
/// # Examples
///
/// ```
/// use xzatoma::watcher::generic::event_handler::GenericEventHandler;
///
/// let handler = GenericEventHandler::new(None, None);
/// assert!(handler.plan_directory.is_none());
/// assert!(handler.matcher.is_none());
/// ```
pub struct GenericEventHandler {
    /// Optional event matcher. When `None`, all valid plan events are accepted.
    pub matcher: Option<GenericMatcher>,

    /// Optional directory from which curated plan files are loaded.
    ///
    /// When set, the handler attempts to load `{dir}/{name}-{version}.yaml`
    /// then `{dir}/{name}.yaml` before falling back to the embedded plan.
    pub plan_directory: Option<PathBuf>,
}

impl GenericEventHandler {
    /// Create a new event handler.
    ///
    /// # Arguments
    ///
    /// * `matcher`        - Optional event matcher; `None` accepts all valid plans.
    /// * `plan_directory` - Optional directory for curated on-disk plan files.
    ///
    /// # Returns
    ///
    /// A new `GenericEventHandler` ready to process [`RawKafkaMessage`] values.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzatoma::config::GenericMatchConfig;
    /// use xzatoma::watcher::generic::matcher::GenericMatcher;
    /// use xzatoma::watcher::generic::event_handler::GenericEventHandler;
    ///
    /// let matcher = GenericMatcher::new(GenericMatchConfig {
    ///     action: Some("deploy.*".to_string()),
    ///     name: None,
    ///     version: None,
    /// })
    /// .unwrap();
    ///
    /// let handler = GenericEventHandler::new(Some(matcher), None);
    /// assert!(handler.matcher.is_some());
    /// ```
    pub fn new(matcher: Option<GenericMatcher>, plan_directory: Option<PathBuf>) -> Self {
        Self {
            matcher,
            plan_directory,
        }
    }

    /// Run the five-step pipeline for a single raw Kafka message.
    ///
    /// Returns:
    /// - `Ok(Some(task))` when the message parsed, matched, and produced a task.
    /// - `Ok(None)` when the event was valid but filtered out by the matcher.
    /// - `Err(e)` when parsing, validation, or plan file loading failed.
    ///
    /// # Arguments
    ///
    /// * `msg` - The raw Kafka message to process.
    ///
    /// # Errors
    ///
    /// Returns an error if the payload cannot be parsed as a [`Plan`], if a
    /// located plan file cannot be parsed, or if the resolved plan fails
    /// validation.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzatoma::watcher::generic::event::RawKafkaMessage;
    /// use xzatoma::watcher::generic::event_handler::GenericEventHandler;
    ///
    /// # #[tokio::main]
    /// # async fn main() -> anyhow::Result<()> {
    /// let handler = GenericEventHandler::new(None, None);
    /// let result = handler
    ///     .handle(RawKafkaMessage {
    ///         payload: "not a plan".to_string(),
    ///         topic: "t".to_string(),
    ///         key: None,
    ///     })
    ///     .await;
    /// assert!(result.is_err());
    /// # Ok(())
    /// # }
    /// ```
    pub async fn handle(&self, msg: RawKafkaMessage) -> Result<Option<GenericTask>> {
        // Step 1: Parse the raw payload into a GenericPlanEvent.
        debug!(
            topic = %msg.topic,
            key = ?msg.key,
            bytes = msg.payload.len(),
            "Parsing raw Kafka message into GenericPlanEvent"
        );

        let event = GenericPlanEvent::new(&msg.payload, msg.topic.clone(), msg.key.clone())?;

        info!(
            plan_name = %event.plan.name,
            source_topic = %event.source_topic,
            "Parsed plan event from raw Kafka message"
        );

        // Step 2: Evaluate the optional event matcher.
        if let Some(matcher) = &self.matcher {
            if !matcher.should_process(&event) {
                debug!(
                    plan_name = %event.plan.name,
                    "Event did not satisfy configured match criteria; skipping"
                );
                return Ok(None);
            }
        }

        // Step 3: Resolve plan from disk directory if configured.
        let resolved_plan = if let Some(dir) = &self.plan_directory {
            self.resolve_plan_from_directory(&event, dir)?
        } else {
            event.plan.clone()
        };

        // Step 4: Validate the resolved plan.
        PlanParser::validate(&resolved_plan)?;

        // Step 5: Derive instruction and build the task.
        let instruction = resolved_plan.to_instruction();

        info!(
            plan_name = %resolved_plan.name,
            step_count = resolved_plan.steps.len(),
            "Plan resolved and validated; building GenericTask"
        );

        Ok(Some(GenericTask {
            plan: resolved_plan,
            instruction,
            correlation_key: msg.key,
            received_at: event.received_at,
        }))
    }

    /// Attempt to load a curated plan file from `dir` for the given event.
    ///
    /// Priority order:
    /// 1. `{dir}/{plan.name}-{version}.yaml` when `event.version` is `Some`.
    /// 2. `{dir}/{plan.name}.yaml` as a name-only fallback.
    /// 3. The embedded plan from the event when no file is found.
    ///
    /// Returns `Err` if a file exists at a candidate path but cannot be parsed.
    fn resolve_plan_from_directory(&self, event: &GenericPlanEvent, dir: &Path) -> Result<Plan> {
        let plan_name = &event.plan.name;

        // Priority 1: versioned file.
        if let Some(version) = &event.version {
            let versioned_path = dir.join(format!("{plan_name}-{version}.yaml"));
            if versioned_path.exists() {
                debug!(
                    path = %versioned_path.display(),
                    "Loading versioned plan file from directory"
                );
                return PlanParser::from_file(&versioned_path);
            }
        }

        // Priority 2: name-only file.
        let name_path = dir.join(format!("{plan_name}.yaml"));
        if name_path.exists() {
            debug!(
                path = %name_path.display(),
                "Loading name-only plan file from directory"
            );
            return PlanParser::from_file(&name_path);
        }

        // Priority 3: fall back to the embedded plan.
        debug!(
            plan_name = %plan_name,
            "No plan file found in directory; using embedded plan from payload"
        );
        Ok(event.plan.clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::GenericMatchConfig;
    use crate::watcher::generic::matcher::GenericMatcher;
    use std::fs;
    use tempfile::tempdir;

    // ---------------------------------------------------------------------------
    // Shared helpers
    // ---------------------------------------------------------------------------

    const VALID_YAML: &str = "name: deploy\nsteps:\n  - name: apply\n    action: kubectl apply\n";
    const VALID_YAML_WITH_ACTION: &str =
        "name: deploy\naction: deploy-prod\nsteps:\n  - name: apply\n    action: kubectl apply\n";
    const VALID_YAML_WITH_VERSION: &str =
        "name: deploy\nversion: v1.0\nsteps:\n  - name: apply\n    action: kubectl apply\n";

    fn raw_msg(payload: &str) -> RawKafkaMessage {
        RawKafkaMessage {
            payload: payload.to_string(),
            topic: "test.topic".to_string(),
            key: None,
        }
    }

    fn raw_msg_with_key(payload: &str, key: &str) -> RawKafkaMessage {
        RawKafkaMessage {
            payload: payload.to_string(),
            topic: "test.topic".to_string(),
            key: Some(key.to_string()),
        }
    }

    fn accept_all_matcher() -> GenericMatcher {
        GenericMatcher::new(GenericMatchConfig::default()).unwrap()
    }

    fn action_matcher(action: &str) -> GenericMatcher {
        GenericMatcher::new(GenericMatchConfig {
            action: Some(action.to_string()),
            name: None,
            version: None,
        })
        .unwrap()
    }

    // ---------------------------------------------------------------------------
    // Task 2.6 required tests
    // ---------------------------------------------------------------------------

    #[tokio::test]
    async fn test_handle_valid_plan_no_matcher_no_directory() {
        let handler = GenericEventHandler::new(None, None);
        let task = handler.handle(raw_msg(VALID_YAML)).await.unwrap();

        let task = task.expect("expected Some(task) for a valid plan with no matcher");
        assert_eq!(task.plan.name, "deploy");
        assert!(
            !task.instruction.is_empty(),
            "instruction must be non-empty"
        );
        assert!(
            task.instruction.contains("deploy"),
            "instruction must reference the plan name"
        );
    }

    #[tokio::test]
    async fn test_handle_propagates_correlation_key() {
        let handler = GenericEventHandler::new(None, None);
        let task = handler
            .handle(raw_msg_with_key(VALID_YAML, "corr-key-42"))
            .await
            .unwrap()
            .expect("expected Some(task)");

        assert_eq!(
            task.correlation_key.as_deref(),
            Some("corr-key-42"),
            "task.correlation_key must match the Kafka message key"
        );
    }

    #[tokio::test]
    async fn test_handle_invalid_payload_returns_err() {
        let handler = GenericEventHandler::new(None, None);
        let result = handler.handle(raw_msg("not a valid plan at all")).await;
        assert!(
            result.is_err(),
            "parse failure must propagate as Err from handle"
        );
    }

    #[tokio::test]
    async fn test_handle_matcher_passes() {
        // Matcher configured to accept "deploy-prod"; plan carries that action.
        let handler = GenericEventHandler::new(Some(action_matcher("deploy-prod")), None);
        let task = handler
            .handle(raw_msg(VALID_YAML_WITH_ACTION))
            .await
            .unwrap();
        assert!(
            task.is_some(),
            "matcher must accept event whose action matches pattern"
        );
    }

    #[tokio::test]
    async fn test_handle_matcher_filters_out() {
        // Matcher configured to accept "rollback.*"; plan carries "deploy-prod".
        let handler = GenericEventHandler::new(Some(action_matcher("rollback.*")), None);
        let result = handler
            .handle(raw_msg(VALID_YAML_WITH_ACTION))
            .await
            .unwrap();
        assert_eq!(
            result, None,
            "matcher must return Ok(None) for events that do not match"
        );
    }

    #[tokio::test]
    async fn test_handle_with_plan_directory_name_only_fallback() {
        // Versioned file does not exist; handler must load the name-only file.
        let dir = tempdir().unwrap();
        let name_only_yaml = "name: deploy\nsteps:\n  - name: s1\n    action: echo from-disk\n";
        fs::write(dir.path().join("deploy.yaml"), name_only_yaml).unwrap();

        let handler = GenericEventHandler::new(None, Some(dir.path().to_path_buf()));
        // Payload has no version, so only the name-only file can match.
        let task = handler
            .handle(raw_msg(VALID_YAML))
            .await
            .unwrap()
            .expect("expected Some(task)");

        assert_eq!(
            task.plan.steps[0].action, "echo from-disk",
            "handler must use the name-only file from disk"
        );
    }

    #[tokio::test]
    async fn test_handle_with_plan_directory_versioned_plan_takes_priority() {
        // Both versioned and name-only files exist; versioned file must win.
        let dir = tempdir().unwrap();
        let versioned_yaml = "name: deploy\nsteps:\n  - name: s1\n    action: echo versioned\n";
        let name_only_yaml = "name: deploy\nsteps:\n  - name: s1\n    action: echo name-only\n";
        fs::write(dir.path().join("deploy-v1.0.yaml"), versioned_yaml).unwrap();
        fs::write(dir.path().join("deploy.yaml"), name_only_yaml).unwrap();

        let handler = GenericEventHandler::new(None, Some(dir.path().to_path_buf()));
        // VALID_YAML_WITH_VERSION sets plan version = "v1.0"
        let task = handler
            .handle(raw_msg(VALID_YAML_WITH_VERSION))
            .await
            .unwrap()
            .expect("expected Some(task)");

        assert_eq!(
            task.plan.steps[0].action, "echo versioned",
            "versioned file must take priority over name-only file"
        );
    }

    #[tokio::test]
    async fn test_handle_with_plan_directory_no_file_uses_payload_plan() {
        // Directory exists but contains no matching plan file; embedded plan used.
        let dir = tempdir().unwrap();

        let handler = GenericEventHandler::new(None, Some(dir.path().to_path_buf()));
        let task = handler
            .handle(raw_msg(VALID_YAML))
            .await
            .unwrap()
            .expect("expected Some(task)");

        assert_eq!(
            task.plan.name, "deploy",
            "handler must fall back to the embedded payload plan"
        );
        assert_eq!(
            task.plan.steps[0].action, "kubectl apply",
            "embedded plan steps must be preserved"
        );
    }

    #[tokio::test]
    async fn test_handle_received_at_is_set() {
        let handler = GenericEventHandler::new(None, None);
        let before = Utc::now();
        let task = handler
            .handle(raw_msg(VALID_YAML))
            .await
            .unwrap()
            .expect("expected Some(task)");
        let after = Utc::now();

        assert!(
            task.received_at >= before,
            "received_at must not be before construction"
        );
        assert!(
            task.received_at <= after,
            "received_at must not be after construction"
        );
    }

    // ---------------------------------------------------------------------------
    // Additional coverage
    // ---------------------------------------------------------------------------

    #[tokio::test]
    async fn test_handle_accept_all_matcher_passes_all_valid_events() {
        let handler = GenericEventHandler::new(Some(accept_all_matcher()), None);
        let task = handler.handle(raw_msg(VALID_YAML)).await.unwrap();
        assert!(task.is_some(), "accept-all matcher must pass valid events");
    }

    #[tokio::test]
    async fn test_handle_instruction_contains_step_action() {
        let handler = GenericEventHandler::new(None, None);
        let task = handler.handle(raw_msg(VALID_YAML)).await.unwrap().unwrap();
        assert!(
            task.instruction.contains("kubectl apply"),
            "instruction must include the plan step action"
        );
    }

    #[tokio::test]
    async fn test_handle_missing_key_sets_correlation_key_to_none() {
        let handler = GenericEventHandler::new(None, None);
        let task = handler.handle(raw_msg(VALID_YAML)).await.unwrap().unwrap();
        assert!(
            task.correlation_key.is_none(),
            "correlation_key must be None when the Kafka message has no key"
        );
    }

    #[tokio::test]
    async fn test_handle_with_plan_directory_parse_error_propagates() {
        // File exists but contains invalid YAML; handler must return Err.
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("deploy.yaml"), "not: valid: plan: syntax:").unwrap();

        let handler = GenericEventHandler::new(None, Some(dir.path().to_path_buf()));
        let result = handler.handle(raw_msg(VALID_YAML)).await;
        assert!(
            result.is_err(),
            "handler must propagate parse error from disk plan file"
        );
    }

    #[tokio::test]
    async fn test_handle_result_json_payload_returns_err() {
        // A GenericPlanResult JSON must fail to parse and return Err.
        let result_json = r#"{
            "id": "01JRESULT",
            "event_type": "result",
            "trigger_event_id": "01JTRIGGER",
            "success": true,
            "summary": "done",
            "timestamp": "2025-01-01T00:00:00Z"
        }"#;
        let handler = GenericEventHandler::new(None, None);
        let result = handler.handle(raw_msg(result_json)).await;
        assert!(
            result.is_err(),
            "result event JSON must fail to parse as a Plan"
        );
    }

    #[tokio::test]
    async fn test_handle_empty_steps_returns_err() {
        let handler = GenericEventHandler::new(None, None);
        let result = handler.handle(raw_msg("name: no-steps\nsteps: []\n")).await;
        assert!(
            result.is_err(),
            "plan with empty steps must fail validation"
        );
    }

    #[tokio::test]
    async fn test_handle_json_payload_works() {
        let json = r#"{"name":"json-plan","steps":[{"name":"s1","action":"echo json"}]}"#;
        let handler = GenericEventHandler::new(None, None);
        let task = handler.handle(raw_msg(json)).await.unwrap().unwrap();
        assert_eq!(task.plan.name, "json-plan");
    }
}
